services:
  nginx:
    image: nginx:alpine
    container_name: guarita_nginx
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  api1:
    image: ghcr.io/macielti/guarita:sha-269dc72
    container_name: guarita_api1
    restart: unless-stopped
    volumes:
      - ./resources/config.edn:/app/resources/config.edn
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"

  api2:
    image: ghcr.io/macielti/guarita:sha-269dc72
    container_name: guarita_api2
    restart: unless-stopped
    volumes:
      - ./resources/config.edn:/app/resources/config.edn
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"
